# Generated by Django 6.0.7 on 2026-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Senior Full-Stack Engineer — Stellar Labs', max_length=200)),
                ('year_range', models.CharField(help_text='e.g. 2023 — Present', max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Experience entries',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech', models.CharField(blank=True, help_text='Comma-separated tech tags, e.g. React, Node.js, MongoDB', max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must match a project tech tag exactly, e.g. React', max_length=100, unique=True)),
                ('level', models.PositiveIntegerField(help_text='Proficiency percentage, 0-100')),
            ],
            options={
                'verbose_name': 'Skill override',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(help_text='Shown in the avatar circle, e.g. AM', max_length=5)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, help_text='Their role, e.g. Product Lead', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
