# Generated by Django 6.0.7 on 2026-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, help_text='e.g. 2024 or March 2024', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, help_text='e.g. 2024', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the credential')),
                ('image', models.ImageField(blank=True, help_text='Badge or certificate image', null=True, upload_to='certifications/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Talk or workshop title', max_length=200)),
                ('event', models.CharField(blank=True, help_text='e.g. PyCon Kenya 2024', max_length=200)),
                ('date', models.CharField(blank=True, help_text='e.g. March 2024', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, help_text='Slides, recording, or event page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'Talks & workshops',
                'ordering': ['order', 'id'],
            },
        ),
    ]
